#!/bin/sh

eval last=\${$#}

# Start remote camera
wget -O /dev/zero "http://192.168.0.12:8080/app/startMyWebcam"

# Get the picture file
wget -O $last "http://192.168.0.12:8080/webcam.jpg"

# Stop remote camera
wget -O /dev/zero "http://192.168.0.12:8080/app/stopMyWebcam"
